### ISSUE TITLE
ERRO mme.localdomain 

### ISSUE THREAD

**Issue by omeshF** [omec-project/c3po#29]
Hello

In the section RUN C3PO MODULES after following all the previous steps, 
as I run the following command 
 #cd {installation_root}/hss
        #./bin/hss -j conf/hss.json

I get the following error. 
**ERROR  mme.localdomain: Going to ZOMBIE state (no more activity)**

Any advice on a fix will be highly appreciated. 
Thank you

**Comment by micpez** [comment]
@omeshF is OpenMME configured/installed (according https://github.com/omec-project/openmme/blob/master/README.txt) and running?
When OpenMME starts and connects, you should see something similar to this:
```
06:24:03  ERROR  mme.localdomain: Going to ZOMBIE state (no more activity)
06:24:03  NOTI   'STATE_CLOSED'	-> 'STATE_ZOMBIE' (terminated)	'mme.localdomain'
06:24:32  NOTI   Connected to 'mme.localdomain' (TCP,soc#27), remote capabilities: 
06:24:32  NOTI   Capabilities-Exchange-Request(257) ...
06:24:32  NOTI   No TLS protection negotiated with peer 'mme.localdomain'.
06:24:32  NOTI   'STATE_CLOSED'	-> 'STATE_OPEN'	'mme.localdomain
```

**Comment by dzvancuks** [comment]
In C3PO video demo devs also had this error and just ignored it. In my testing I was able to connect to HSS using SCTP, just ignored this error message. Probably it is caused by different Diameter Identity host name when you configure hss and data_provisioning* scripts.

According to sources HSS creates peer using "MME_IDENTITY" environment variable. Otherwise hardcoded "mme.localdomain" is used.
I think it should be provided via hss.json instead of environment.

**Comment by dchard** [comment]
> I think it should be provided via hss.json instead of environment.

You are correct. On my end this error message is also there, not causing any actual errors, I am also using the HSS via SCTP. The mmehost and mmeidentity are both configured in the HSS, yet this error message is present.
